### ISSUE TITLE
Optionality of "Related Document"

### ISSUE THREAD

**Issue by nkrondraf** [hl7-eu/eps#8]
I'm not sure if this is the right place to ask since I'm referring to https://webgate.ec.europa.eu/fpfis/wikis/display/EHDSI/05.01.+Create+the+MyHealth@EU+Patient+Summary+content

The section "Related Document" (line 128) has an optionality of "Mandatory" which is not clear to me. How should this be handled if there is no parent document available?

**Comment by gcangioli** [comment]
I'd say it is there for historical reasons, when it was assumed that a CDA Patient Summary conforming to the epSOS specificaiton would have been derived from an already existing PS. Moreover it is requested that aslo a "printable" form (a PDF) is provided. relatedDocument is also used to refer also the CDA with the embedded PDF.

This is not present in the eHN data set we are referring to..

I suggest you bring this issue to the eHMSEG STF, (sincerly I don't like the way it is expressed :-) )
